travis:
  secure:
    BINSTAR_TOKEN: jC/QexhYffz5QZBf+YixICnWbsTv8tfZyELe/mWqVYtWZ7xCcp9Mw3nNfRijEC+mO4BYdKbe7kpow8GmYy/oaS/VFb8V1C8CMg3GmOKJrWbTKvZYacy8KjwsOLs1XnFC/4e4uvG36ZVgwJMikNoPBn2/z8KIIB8Qh6dsmSlHfnXUljad+PnKrokHnVMwY62CysXPJMNg/I721dW4O0XFUNNqUEHwPy7fdtL75V4pQS7Vc3Wnyeb2SbDAiACs21EEUX++X10TvfP3GOJLGcIq8nM1mbPB+/vq/ei+HFxL74xiRiAAj2kEW7iL6Iut+Lw+R7sc/boIWXjqKlqIq2pUbuopOKakKF4N3QhXXTG8KcHLp24kNMKsjIE6idLEluNNWOQMQhotWqq6xhxfytQuBSsyaMVerELaEFxD0Zb8eVO/p5q06HtLcosvCEQ4wwLYELG1fwYS29164yu/ZR7Ua8sjpnGceRPf3t2rSiPWAlEy8x0oAoaFS2wvGiefzN/v9jZN0xGaz2oTKH6AiuF8GdVThbfe7+UnGPh00baS/pziudo4p+WHZT9+EaNJbQTwqa9MlMxf13KQ7panxTp9uDW1VZPpj7MfqPi5YTG6jCoMsmyZa62OBDbfHh+A+I93sRyeW7CcXk8d1JhzPfTeCOF4RZtLfdXFkbyF74rZYZ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
